### ISSUE TITLE
Update/Scale the application

### ISSUE THREAD

**Issue by resouer** [awslabs/amazon-ecs-for-open-application-model#10]
I tried out the demo, it works like charm! Super interesting work.

One issue is, it seems unclear in the doc that how can user update the application, let's say update the image version? Similarly, how can I scale the application by modifying the ManualScaler trait? 

In Kubernetes it normally done by declaratively update the yaml and apply the file. Not sure how can we do it in oam-ecs.

<img width="1318" alt="Screen Shot 2020-03-25 at 8 24 41 PM" src="https://user-images.githubusercontent.com/1701782/77608443-700c4680-6eda-11ea-85dd-a54c0400ef81.png">

**Comment by clareliguori** [comment]
For both cases, you can re-run the `oam-ecs deploy` command with the same inputs and it will update the CloudFormation stack.  The tool doesn't follow the [spec guidance](https://github.com/oam-dev/spec/blob/master/6.application_configuration.md#releases) of treating component schematics as immutable, so they can be updated with a new image.  I'll add some notes in the readme about that.

**Comment by clareliguori** [comment]
Added to readme in https://github.com/awslabs/amazon-ecs-for-open-application-model/commit/f812c08e022db819c2c4d6f970a592c213a27e3d
